# Generated by Django 3.1.5 on 2021-03-22 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('college', models.CharField(blank=True, default='Indian Institute of Information Technology, Una', max_length=60)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('branch', models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'IT')], max_length=3)),
                ('rollNo', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('profile_pic', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
