# Generated by Django 3.1.5 on 2021-03-23 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210322_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('details', models.TextField()),
                ('description', models.CharField(max_length=200)),
                ('poster', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
