# Generated by Django 3.1.7 on 2021-04-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210413_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
