# Generated by Django 3.1.7 on 2021-04-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_restricted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restricted',
        ),
    ]
