# Generated by Django 3.1.7 on 2021-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_category_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)]),
        ),
    ]
