# Generated by Django 3.1.7 on 2021-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210423_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'IT')], default='CSE', max_length=3),
        ),
    ]
