# Generated by Django 3.1.7 on 2021-04-25 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_user_is_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rollNo',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
